#!/usr/bin/env node
// Builds the single compiled stylesheet the design-sync converter ships as
// `cssEntry`. The site's CSS can't be consumed from source: `app/globals.css`
// starts with `@import 'tailwindcss'` (needs the Tailwind v4 compiler) and the
// brand fonts come from `next/font/google`, which only emits @font-face at
// Next build time.
//
// Output: web/.ds-css/compiled.css — Tailwind utilities for the whole
// component tree + brand tokens + globals + self-hosted @font-face rules,
// with font URLs pointing at ./fonts/ next to it.

import { cpSync, existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const REPO = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const WEB = join(REPO, 'web');
const OUT_DIR = join(WEB, '.ds-css');
const NEXT_STATIC = join(WEB, '.next', 'static');

if (!existsSync(NEXT_STATIC)) {
  console.error(
    `[CSS_GEN] ${NEXT_STATIC} missing — run \`npm --workspace web run build\` first ` +
      `(next/font emits @font-face only at build time).`,
  );
  process.exit(1);
}

rmSync(OUT_DIR, { recursive: true, force: true });
mkdirSync(join(OUT_DIR, 'fonts'), { recursive: true });

// ── 1. Harvest @font-face rules from the Next build output ────────────────
// next/font self-hosts Google Fonts into .next/static/media and emits the
// @font-face rules into one of the built stylesheets.
const cssFiles = readdirSync(join(NEXT_STATIC, 'css')).filter((f) => f.endsWith('.css'));
const faces = [];
for (const f of cssFiles) {
  const text = readFileSync(join(NEXT_STATIC, 'css', f), 'utf8');
  for (const m of text.matchAll(/@font-face\s*\{[^}]*\}/g)) faces.push(m[0]);
}
if (!faces.length) {
  console.error('[CSS_GEN] no @font-face rules found in the Next build output');
  process.exit(1);
}

// Copy each referenced woff2 next to the stylesheet and repoint the url().
const copied = new Set();
const localFaces = [...new Set(faces)].map((rule) =>
  rule.replace(/url\((\/_next\/static\/media\/([^)]+))\)/g, (_all, _abs, file) => {
    const src = join(NEXT_STATIC, 'media', file);
    if (!existsSync(src)) {
      console.error(`[CSS_GEN] referenced font missing: ${src}`);
      process.exit(1);
    }
    if (!copied.has(file)) {
      cpSync(src, join(OUT_DIR, 'fonts', file));
      copied.add(file);
    }
    return `url(./fonts/${file})`;
  }),
);

const families = [...new Set(localFaces.map((r) => /font-family:\s*([^;]+);/.exec(r)?.[1]?.trim()))];

// The site wires families to CSS variables through next/font's generated
// classNames on <html>; nothing in the component tree defines them. Bind them
// here so components render in the real brand faces outside Next.
const fontsCss = `/* Generated by .design-sync/build-css.mjs — do not edit. */
${localFaces.join('\n')}

:root {
  --font-geist-sans: 'Inter', ui-sans-serif, system-ui, sans-serif;
  --font-heading: 'Sora', ui-sans-serif, system-ui, sans-serif;
  --font-geist-mono: 'Geist Mono', ui-monospace, SFMono-Regular, Menlo, monospace;
}
`;
writeFileSync(join(OUT_DIR, 'fonts.css'), fontsCss);

// ── 2. Compile the Tailwind + globals + brand entry ───────────────────────
// Explicit @source: automatic detection is rooted at the compiler's cwd, which
// is not the component tree we actually ship.
writeFileSync(
  join(OUT_DIR, 'entry.css'),
  `@import '../app/globals.css';
@source '../components/**/*.{ts,tsx}';
@source '../app/**/*.{ts,tsx}';
@import './fonts.css';
`,
);

// Bare specifiers resolve from this script's location up into the repo root
// node_modules, where the site's own postcss + Tailwind v4 are installed —
// the compiler that produces the CSS is the one the site itself ships with.
const postcss = (await import('postcss')).default;
const tailwind = (await import('@tailwindcss/postcss')).default;

const entryPath = join(OUT_DIR, 'entry.css');
const result = await postcss([tailwind()]).process(readFileSync(entryPath, 'utf8'), {
  from: entryPath,
  to: join(OUT_DIR, 'compiled.css'),
});
writeFileSync(join(OUT_DIR, 'compiled.css'), result.css);

console.error(
  `[CSS_GEN] compiled.css ${(result.css.length / 1024).toFixed(0)}KB · ` +
    `${copied.size} font files · families: ${families.join(', ')}`,
);
